name: Temp Action
on:
  workflow_run:
    workflows: [Checks]
    types:
      - completed

jobs:
  get-event-details:
    name: Build and Publish Image
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Workflow run: ${{ github.event.workflow_run.actor }}"
